- hosts: all
  name: Test
  rules:
    - name: An automatic remediation rule
      condition: event.outage == true
      action:
        run_job_template:
          name: remediate_outage.yml
          organization: Default

    - name: Print event with linux
      condition: event.target_os == "linux"
      action:
        debug:

    - name: Say Hello
      condition: event.payload.message == "Ansible is super cool"

  ## Define the action we should take should the condition be met

      action:
        run_job_template: 
          name: say-what.yml
          organization: Default

            
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for


