- hosts: all

  rules:
    - name: An automatic remediation rule
      condition: event.outage == true
      action:
        run_playbook:
          name: remediate_outage.yml

    - name: Print event with linux
      condition: event.target_os == "linux" or
      action:
        debug:
